// <auto-generated />
using System;
using Convocation.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Convocation.DataAccess.Migrations
{
    [DbContext(typeof(ConvocationDbContext))]
    [Migration("20260530163257_FixRoleAndDistribution")]
    partial class FixRoleAndDistribution
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Convocation.Entities.DistributionLog", b =>
                {
                    b.Property<int>("DistributionLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistributionLogId"));

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("DistributionTaskId")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelivered")
                        .HasColumnType("bit");

                    b.Property<bool>("IsQrVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("int");

                    b.Property<int?>("ParticipantId1")
                        .HasColumnType("int");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("int");

                    b.Property<int?>("RegistrationId1")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("int");

                    b.Property<int?>("UserAccountId1")
                        .HasColumnType("int");

                    b.HasKey("DistributionLogId");

                    b.HasIndex("DistributionTaskId");

                    b.HasIndex("EventId");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("ParticipantId1");

                    b.HasIndex("RegistrationId1");

                    b.HasIndex("UserAccountId");

                    b.HasIndex("UserAccountId1");

                    b.HasIndex("RegistrationId", "ActionType")
                        .IsUnique();

                    b.ToTable("DistributionLog");
                });

            modelBuilder.Entity("Convocation.Entities.DistributionTask", b =>
                {
                    b.Property<int>("DistributionTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistributionTaskId"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DistributionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("DistributionTaskId");

                    b.HasIndex("EventId");

                    b.ToTable("DistributionTask");
                });

            modelBuilder.Entity("Convocation.Entities.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<decimal>("BaseFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("GuestFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxGuestAllowed")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RegistrationtartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("EventId");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("Convocation.Entities.FoodMenu", b =>
                {
                    b.Property<int>("FoodMenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodMenuId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MenuItems")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MenuName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("FoodMenuId");

                    b.ToTable("FoodMenu");
                });

            modelBuilder.Entity("Convocation.Entities.Guest", b =>
                {
                    b.Property<int>("GuestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuestId"));

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("int");

                    b.Property<string>("Relation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GuestId");

                    b.HasIndex("RegistrationId");

                    b.ToTable("Guest");
                });

            modelBuilder.Entity("Convocation.Entities.Models.DistributionItem", b =>
                {
                    b.Property<int>("DistributionItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistributionItemId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("RequiresQrValidation")
                        .HasColumnType("bit");

                    b.HasKey("DistributionItemId");

                    b.ToTable("DistributionItem");
                });

            modelBuilder.Entity("Convocation.Entities.OperationActivityLog", b =>
                {
                    b.Property<int>("OperationActivityLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OperationActivityLogId"));

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserAccountId")
                        .HasColumnType("int");

                    b.HasKey("OperationActivityLogId");

                    b.HasIndex("UserAccountId");

                    b.ToTable("OperationActivityLog");
                });

            modelBuilder.Entity("Convocation.Entities.Participant", b =>
                {
                    b.Property<int>("ParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParticipantId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsEligible")
                        .HasColumnType("bit");

                    b.Property<string>("Program")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Session")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("int");

                    b.HasKey("ParticipantId");

                    b.HasIndex("UserAccountId")
                        .IsUnique();

                    b.ToTable("Participant");
                });

            modelBuilder.Entity("Convocation.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PaymentId");

                    b.HasIndex("RegistrationId")
                        .IsUnique();

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("Convocation.Entities.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionId"));

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PermissionId");

                    b.ToTable("Permission", (string)null);
                });

            modelBuilder.Entity("Convocation.Entities.QrPass", b =>
                {
                    b.Property<int>("QrPassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QrPassId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("QrCodeText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QrImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("QrPassId");

                    b.HasIndex("RegistrationId");

                    b.ToTable("QrPass");
                });

            modelBuilder.Entity("Convocation.Entities.Registration", b =>
                {
                    b.Property<int>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistrationId"));

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("GuestCount")
                        .HasColumnType("int");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegistrationStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RegistrationId");

                    b.HasIndex("EventId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("Registration");
                });

            modelBuilder.Entity("Convocation.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "admin"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = " eventmanager"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "staff"
                        },
                        new
                        {
                            RoleId = 4,
                            RoleName = "student"
                        });
                });

            modelBuilder.Entity("Convocation.Entities.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermission", (string)null);
                });

            modelBuilder.Entity("Convocation.Entities.StaffTask", b =>
                {
                    b.Property<int>("StaffTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffTaskId"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DistributionTaskId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("int");

                    b.HasKey("StaffTaskId");

                    b.HasIndex("DistributionTaskId");

                    b.HasIndex("UserAccountId");

                    b.ToTable("StaffTask");
                });

            modelBuilder.Entity("Convocation.Entities.UserAccount", b =>
                {
                    b.Property<int>("UserAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserAccountId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NickName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserAccountId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserAccount");

                    b.HasData(
                        new
                        {
                            UserAccountId = 1,
                            CreatedAt = new DateTime(2026, 5, 17, 19, 18, 41, 790, DateTimeKind.Unspecified),
                            Email = "admin@gmail.com",
                            FullName = "Administrator",
                            IsActive = true,
                            NickName = "admin",
                            PasswordHash = "JAvlGPq9JyTdtvBO6x2llnRI1+gxwIyPqCKAn3THIKk=",
                            Phone = "01700000000",
                            RoleId = 1
                        },
                        new
                        {
                            UserAccountId = 2,
                            CreatedAt = new DateTime(2026, 5, 20, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "eventmanager@gmail.com",
                            FullName = "Event Manager",
                            IsActive = true,
                            NickName = "eventmanager",
                            PasswordHash = "t5Y6r3iXw1hT4Q3Y7e7nNWh0VvM6nZk+3+8v2/2+J1Y=",
                            Phone = "01711111111",
                            RoleId = 2
                        },
                        new
                        {
                            UserAccountId = 3,
                            CreatedAt = new DateTime(2026, 5, 20, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "staff1@gmail.com",
                            FullName = "Staff1",
                            IsActive = true,
                            NickName = "staff1",
                            PasswordHash = "jZae727K08KaOmKSgOaGzww/XVqGr/PKEgIMkjrcbJI=",
                            Phone = "01722222222",
                            RoleId = 3
                        },
                        new
                        {
                            UserAccountId = 4,
                            CreatedAt = new DateTime(2026, 5, 20, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "staff2@gmail.com",
                            FullName = "Staff2",
                            IsActive = true,
                            NickName = "staff2",
                            PasswordHash = "jZae727K08KaOmKSgOaGzww/XVqGr/PKEgIMkjrcbJI=",
                            Phone = "01733333333",
                            RoleId = 3
                        },
                        new
                        {
                            UserAccountId = 5,
                            CreatedAt = new DateTime(2026, 5, 20, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "staff3@gmail.com",
                            FullName = "Staff3",
                            IsActive = true,
                            NickName = "staff3",
                            PasswordHash = "jZae727K08KaOmKSgOaGzww/XVqGr/PKEgIMkjrcbJI=",
                            Phone = "01744444444",
                            RoleId = 3
                        },
                        new
                        {
                            UserAccountId = 6,
                            CreatedAt = new DateTime(2026, 5, 18, 12, 7, 3, 814, DateTimeKind.Unspecified).AddTicks(7314),
                            Email = "maria@gmail.com",
                            FullName = "maria",
                            IsActive = true,
                            PasswordHash = "lK7J++2Yns4Ymn4XLJz0FmkFBJUVK8TB2/KjjX/YVic=",
                            Phone = "01851355382",
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("Convocation.Entities.UserPermission", b =>
                {
                    b.Property<int>("UserPermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserPermissionId"));

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("int");

                    b.HasKey("UserPermissionId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("UserAccountId");

                    b.ToTable("UserPermission", (string)null);
                });

            modelBuilder.Entity("Convocation.Entities.DistributionLog", b =>
                {
                    b.HasOne("Convocation.Entities.DistributionTask", "DistributionTask")
                        .WithMany()
                        .HasForeignKey("DistributionTaskId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Convocation.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Convocation.Entities.Participant", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Convocation.Entities.Participant", null)
                        .WithMany("DistributionLog")
                        .HasForeignKey("ParticipantId1");

                    b.HasOne("Convocation.Entities.Registration", "Registration")
                        .WithMany()
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Convocation.Entities.Registration", null)
                        .WithMany("DistributionLog")
                        .HasForeignKey("RegistrationId1");

                    b.HasOne("Convocation.Entities.UserAccount", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Convocation.Entities.UserAccount", null)
                        .WithMany("DistributionLog")
                        .HasForeignKey("UserAccountId1");

                    b.Navigation("DistributionTask");

                    b.Navigation("Event");

                    b.Navigation("Participant");

                    b.Navigation("Registration");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Convocation.Entities.DistributionTask", b =>
                {
                    b.HasOne("Convocation.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Convocation.Entities.Guest", b =>
                {
                    b.HasOne("Convocation.Entities.Registration", "Registration")
                        .WithMany()
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("Convocation.Entities.OperationActivityLog", b =>
                {
                    b.HasOne("Convocation.Entities.UserAccount", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserAccountId");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Convocation.Entities.Participant", b =>
                {
                    b.HasOne("Convocation.Entities.UserAccount", "UserAccount")
                        .WithOne("Participant")
                        .HasForeignKey("Convocation.Entities.Participant", "UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Convocation.Entities.Payment", b =>
                {
                    b.HasOne("Convocation.Entities.Registration", "Registration")
                        .WithOne("Payment")
                        .HasForeignKey("Convocation.Entities.Payment", "RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("Convocation.Entities.QrPass", b =>
                {
                    b.HasOne("Convocation.Entities.Registration", "Registration")
                        .WithMany()
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("Convocation.Entities.Registration", b =>
                {
                    b.HasOne("Convocation.Entities.Event", "Event")
                        .WithMany("Registration")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Convocation.Entities.Participant", "Participant")
                        .WithMany("Registration")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("Convocation.Entities.RolePermission", b =>
                {
                    b.HasOne("Convocation.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Convocation.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Convocation.Entities.StaffTask", b =>
                {
                    b.HasOne("Convocation.Entities.DistributionTask", "DistributionTask")
                        .WithMany()
                        .HasForeignKey("DistributionTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Convocation.Entities.UserAccount", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DistributionTask");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Convocation.Entities.UserAccount", b =>
                {
                    b.HasOne("Convocation.Entities.Role", "Role")
                        .WithMany("UserAccounts")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Convocation.Entities.UserPermission", b =>
                {
                    b.HasOne("Convocation.Entities.Permission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Convocation.Entities.UserAccount", "UserAccount")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Convocation.Entities.Event", b =>
                {
                    b.Navigation("Registration");
                });

            modelBuilder.Entity("Convocation.Entities.Participant", b =>
                {
                    b.Navigation("DistributionLog");

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("Convocation.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("Convocation.Entities.Registration", b =>
                {
                    b.Navigation("DistributionLog");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Convocation.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserAccounts");
                });

            modelBuilder.Entity("Convocation.Entities.UserAccount", b =>
                {
                    b.Navigation("DistributionLog");

                    b.Navigation("Participant");

                    b.Navigation("UserPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
